export const DISPLAY = "display";
export const BACKGROUND = "background";
export const FILTER = "filter";
export const TEXT_TRANSFORM = "text-transform";
export const DISPLAY_NONE = "none";
export const LOWERCASE = "lowercase";

export const STORAGE_KEY = "youtube_elements";

export const PAGE_TYPES = {
    HOME: "home",
    SUBSCRIPTIONS: "subscriptions",
    VIDEO: "video",
    SEARCH: "search",
    TRENDING: "trending",
    DOWNLOADS: "downloads",
    CHANNEL: "channel",
} as const;

export type PageType = typeof PAGE_TYPES[keyof typeof PAGE_TYPES];

export interface YoutubeElement {
    id: string;
    selector: string;
    checked: boolean; // default state
    property?: string;
    style?: string;
    pageTypes: PageType[];
    label?: string; // Human readable label
    category?: string; // To group them in the UI
}

export const DEFAULT_ELEMENTS: YoutubeElement[] = [
    // --- Header ---
    {
        id: "logo",
        selector: "//ytd-topbar-logo-renderer",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [],
        label: "YouTube Logo",
        category: "Header",
    },
    {
        id: "microphone-search",
        selector: "//*[@id='voice-search-button']",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [],
        label: "Microphone Icon",
        category: "Header",
    },
    {
        id: "create",
        selector: "//div[@id='buttons' and contains(@class, 'ytd-masthead')]/ytd-button-renderer",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [],
        label: "Create (Plus) Icon",
        category: "Header",
    },
    {
        id: "notification-button",
        selector: "//ytd-notification-topbar-button-renderer",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [],
        label: "Notifications Icon",
        category: "Header",
    },
    {
        id: "profile-sign-out",
        selector: "//ytd-compact-link-renderer/a[@href='/logout']",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [],
        label: "Sign Out Button (Profile)",
        category: "Header",
    },


    // --- Home ---
    {
        id: "scheduled-videos",
        selector:
            "//ytd-rich-item-renderer[.//ytd-thumbnail-overlay-time-status-renderer[@overlay-style='UPCOMING']]",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [PAGE_TYPES.HOME],
        label: "Scheduled Videos",
        category: "Home",
    },
    {
        id: "live-videos",
        selector:
            "//ytd-rich-item-renderer[.//div[@id='meta']/ytd-badge-supported-renderer[not(@hidden)]]",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [PAGE_TYPES.HOME],
        label: "Live Videos (Livestreams)",
        category: "Home",
    },
    {
        id: "tabs",
        selector:
            "//ytd-feed-filter-chip-bar-renderer[@component-style='FEED_FILTER_CHIP_BAR_STYLE_TYPE_DEFAULT']/..",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [PAGE_TYPES.HOME],
        label: "Tabs / Topic Chips",
        category: "Home",
    },
    {
        id: "home-posts",
        selector: "//ytd-rich-section-renderer[.//ytd-post-renderer]",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [PAGE_TYPES.HOME],
        label: "Community Posts",
        category: "Home",
    },
    {
        id: "home-shorts",
        selector: "//ytd-rich-section-renderer[.//ytm-shorts-lockup-view-model]",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [PAGE_TYPES.HOME],
        label: "Shorts Section",
        category: "Home",
    },
    {
        id: "home-news",
        selector: "//ytd-rich-section-renderer[not(.//ytm-shorts-lockup-view-model) and not(.//div[contains(@class, 'button-container') and not(@hidden)][.//*[local-name() = 'svg']//*[local-name() = 'path' and @d='m18 9.28-6.35 6.35-6.37-6.35.72-.71 5.64 5.65 5.65-5.65z']])] | //ytd-rich-section-renderer[.//a[@href='/feed/news_destination']]", // Updated with clearer news selector if possible, keeping user's complex one
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [PAGE_TYPES.HOME],
        label: "Breaking News",
        category: "Home",
    },
    {
        id: "home-trending",
        selector: "//ytd-rich-section-renderer[.//div[contains(@class, 'button-container') and not(@hidden)][.//*[local-name() = 'svg']//*[local-name() = 'path' and @d='m18 9.28-6.35 6.35-6.37-6.35.72-.71 5.64 5.65 5.65-5.65z']]]",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [PAGE_TYPES.HOME],
        label: "Trending Shelf",
        category: "Home",
    },
    {
        id: "home-playables",
        selector: "//ytd-rich-section-renderer[.//a[contains(@href, '/playables')]]",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [PAGE_TYPES.HOME],
        label: "Playables",
        category: "Home",
    },
    {
        id: "home-primetime-movies",
        selector: "//ytd-rich-section-renderer[.//a[@href='/feed/storefront']]",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [PAGE_TYPES.HOME],
        label: "Primetime Movies",
        category: "Home",
    },
    {
        id: "playlist-mix",
        selector: "//ytd-rich-item-renderer[.//ytd-playlist-thumbnail[not(@hidden)]] | //ytd-rich-item-renderer[.//a[contains(@href, 'start_radio=1')]]",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [PAGE_TYPES.HOME],
        label: "Mix Playlists",
        category: "Home",
    },
    {
        id: "podcast-playlist",
        selector: "//ytd-rich-item-renderer[.//a[contains(@href, 'pp=')]]",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [PAGE_TYPES.HOME],
        label: "Podcasts",
        category: "Home",
    },
    {
        id: "viewed-videos",
        selector: "//ytd-rich-item-renderer[.//div[@id='progress'][contains(@style, 'width: 100%')]]",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [PAGE_TYPES.HOME],
        label: "Fully Viewed Videos",
        category: "Home",
    },
    {
        id: "partially-viewed-videos",
        selector: "//ytd-rich-item-renderer[.//ytd-thumbnail[not(@is-live-video)]//div[@id='progress']]",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [PAGE_TYPES.HOME],
        label: "Partially Viewed Videos",
        category: "Home",
    },
    {
        id: "members-only",
        selector: "//ytd-rich-item-renderer[.//*[local-name() = 'svg']//*[local-name() = 'path' and @d='M8 1C4.13 1 1 4.13 1 8s3.13 7 7 7 7-3.13 7-7-3.13-7-7-7Zm2.47 10.5L7.99 9.94 5.5 11.5l.67-2.97L4 6.5l2.87-.22L8.01 3.5l1.12 2.78L12 6.5 9.82 8.53l.65 2.97Z']]",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [PAGE_TYPES.HOME],
        label: "Members Only Content",
        category: "Home",
    },
    {
        id: "all-videos",
        selector: "//*[@page-subtype='home']/div[@id='primary']",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [PAGE_TYPES.HOME],
        label: "Hide All Videos (Home Feed)",
        category: "Home",
    },


    // --- Sidebar ---
    {
        id: "sidebar",
        selector:
            "//tp-yt-app-drawer | //ytd-mini-guide-renderer | //yt-icon-button[@id='guide-button']",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [],
        label: "Sidebar (Drawer)",
        category: "Sidebar",
    },
    {
        id: "home-btn",
        selector: "//ytd-guide-entry-renderer[a[@href='/']] | //ytd-mini-guide-entry-renderer[a[@href='/']]",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [],
        label: "Home Button",
        category: "Sidebar",
    },
    {
        id: "shorts-sidebar",
        selector: "//ytd-guide-entry-renderer[a[@title='Shorts']] | //ytd-mini-guide-entry-renderer[a[@title='Shorts']] | //ytd-guide-entry-renderer[a[@title='YouTube Shorts']] | //ytd-mini-guide-entry-renderer[a[@title='YouTube Shorts']]",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [],
        label: "Shorts Button",
        category: "Sidebar",
    },

    // --- Shorts ---
    {
        id: "redirect-shorts",
        selector: "body",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [],
        label: "Redirect Shorts to Normal Player",
        category: "Shorts",
    },
    {
        id: "hide-shorts-everywhere",
        selector:
            "//ytd-rich-item-renderer[.//a[starts-with(@href, '/shorts/')]] | " +
            "//ytd-video-renderer[.//a[starts-with(@href, '/shorts/')]] | " +
            "//ytd-grid-video-renderer[.//a[starts-with(@href, '/shorts/')]] | " +
            "//ytd-reel-shelf-renderer | " +
            "//ytd-rich-shelf-renderer[.//a[starts-with(@href, '/shorts/')]] | " +
            "//ytm-pivot-bar-item-renderer[.//a[starts-with(@href, '/shorts/')]]",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [],
        label: "Hide Shorts Everywhere (Grid/Feed)",
        category: "Shorts",
    },

    {
        id: "subscriptions-btn",
        selector: "//ytd-guide-entry-renderer[a[@href='/feed/subscriptions']] | //ytd-mini-guide-entry-renderer[a[@href='/feed/subscriptions']]",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [],
        label: "Subscriptions Button",
        category: "Sidebar",
    },
    {
        id: "you-btn",
        selector: "(//div[@id='header']/ytd-guide-entry-renderer)[2] | //ytd-mini-guide-entry-renderer[a[@href='/feed/you']]",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [],
        label: "You / Library Button",
        category: "Sidebar",
    },
    {
        id: "playlists-btn",
        selector: "//ytd-guide-entry-renderer[a[@href='/feed/playlists']]",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [],
        label: "Playlists Button",
        category: "Sidebar",
    },
    {
        id: "your-videos-btn",
        selector: "//ytd-guide-entry-renderer[a[starts-with(@href, 'https://studio.youtube.com/channel')]]",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [],
        label: "Your Videos Button",
        category: "Sidebar",
    },
    {
        id: "your-movies-and-tv",
        selector: "//ytd-guide-entry-renderer[a[@href='/feed/storefront?bp=ogUCKAQ%3D']]",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [],
        label: "Your Movies & TV",
        category: "Sidebar",
    },
    {
        id: "your-podcasts",
        selector: "//ytd-guide-entry-renderer[a[@href='/feed/podcasts']]",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [],
        label: "Your Podcasts",
        category: "Sidebar",
    },
    {
        id: "watch-later-btn",
        selector: "//ytd-guide-entry-renderer[a[@href='/playlist?list=WL']]",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [],
        label: "Watch Later Button",
        category: "Sidebar",
    },
    {
        id: "courses",
        selector: "//ytd-guide-entry-renderer[a[@href='/feed/courses']]",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [],
        label: "Your Courses",
        category: "Sidebar",
    },
    {
        id: "liked-videos-btn",
        selector: "//ytd-guide-entry-renderer[a[@href='/playlist?list=LL']]",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [],
        label: "Liked Videos Button",
        category: "Sidebar",
    },
    {
        id: "clips-btn",
        selector: "//ytd-guide-entry-renderer[a[@href='/feed/clips']]",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [],
        label: "My Clips Button",
        category: "Sidebar",
    },
    {
        id: "downloads-btn",
        selector: "//div[@id='section-items']/ytd-guide-downloads-entry-renderer  | //ytd-mini-guide-entry-renderer[a[@href='/feed/downloads']]",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [],
        label: "Downloads Button",
        category: "Sidebar",
    },
    {
        id: "trending-btn",
        selector: "//ytd-guide-entry-renderer[a[@href='/feed/trending']] | //ytd-mini-guide-entry-renderer[a[@href='/feed/trending']]",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [],
        label: "Trending Button",
        category: "Sidebar",
    },
    {
        id: "subscriptions-panel",
        selector: "//ytd-guide-section-renderer[not(.//a[@href='/']) and .//a[@href='/feed/subscriptions']]//ytd-guide-entry-renderer[not(.//a[@href='/feed/subscriptions'])] | //ytd-guide-section-renderer[not(.//a[@href='/']) and .//a[@href='/feed/subscriptions']]//ytd-guide-collapsible-entry-renderer",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [],
        label: "Subscriptions List Panel",
        category: "Sidebar",
    },
    {
        id: "subscriptions-panel-new-indicator",
        selector: "//ytd-guide-entry-renderer[@line-end-style='dot']//div[@id='newness-dot']",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [],
        label: "Subs New Indicator",
        category: "Sidebar",
    },
    {
        id: "explore-panel",
        selector: "(//ytd-guide-section-renderer)[4]",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [],
        label: "Explore Panel",
        category: "Sidebar",
    },
    {
        id: "more-from-youtube-panel",
        selector: "(//ytd-guide-section-renderer)[5]",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [],
        label: "More From YouTube Panel",
        category: "Sidebar",
    },
    {
        id: "settings-panel",
        selector: "(//ytd-guide-section-renderer)[6]",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [],
        label: "Settings Panel",
        category: "Sidebar",
    },
    {
        id: "footer",
        selector: "//ytd-guide-renderer/div[@id='footer']",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [],
        label: "Footer (Copyright)",
        category: "Sidebar",
    },

    // --- General / Global ---
    {
        id: "ads",
        selector:
            "//ytd-ad-slot-renderer/ancestor::ytd-rich-item-renderer | //*[@id='player-ads'] | //ytd-banner-promo-renderer/.. | //div[@id='masthead-ad']",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [],
        label: "Hide Ad Slots",
        category: "General",
    },
    {
        id: "video-previews",
        selector: "//div[@id='video-preview' or @id='mouseover-overlay']",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [],
        label: "Video Previews (Hover)",
        category: "General",
    },
    {
        id: "video-thumbnails",
        selector: "//div[@id='thumbnail'] | //yt-collection-thumbnail-view-model",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [],
        label: "Hide Thumbnails",
        category: "General",
    },
    {
        id: "video-thumbnails-blur",
        selector:
            "//ytd-thumbnail//yt-image | //ytd-playlist-thumbnail | //yt-thumbnail-view-model",
        checked: false,
        property: FILTER,
        style: "blur(10px)",
        pageTypes: [],
        label: "Blur Thumbnails",
        category: "General",
    },
    {
        id: "video-meta-data",
        selector: "//div[@id='metadata-line']",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [],
        label: "Meta Data (Views, Date)",
        category: "General",
    },
    {
        id: "lowercase-title",
        selector:
            "//ytd-watch-metadata//div[@id='title'] | //*[@id='video-title']",
        checked: false,
        property: TEXT_TRANSFORM,
        style: LOWERCASE,
        pageTypes: [],
        label: "Lowercase Titles",
        category: "General",
    },
    {
        id: "download-badge",
        selector: "//p[text()[contains(., 'Downloaded')]]",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [PAGE_TYPES.DOWNLOADS],
        label: "Download Badge",
        category: "General",
    },

    // --- Video Player ---
    {
        id: "video-title",
        selector: "//div[@id='above-the-fold']/div[@id='title']",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [PAGE_TYPES.VIDEO],
        label: "Video Title",
        category: "Video Player",
    },
    {
        id: "video-subscribers",
        selector: "(//div[@id='upload-info'])[1]/yt-formatted-string",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [PAGE_TYPES.VIDEO],
        label: "Subscriber Count",
        category: "Video Player",
    },
    {
        id: "video-subscribe-button",
        selector: "//yt-button-shape[@id='subscribe-button-shape']",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [PAGE_TYPES.VIDEO],
        label: "Subscribe Button",
        category: "Video Player",
    },
    {
        id: "video-subscribed-button",
        selector: "//div[@id='notification-preference-button']",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [PAGE_TYPES.VIDEO],
        label: "Subscribed Notification Bell",
        category: "Video Player",
    },
    {
        id: "video-join-button",
        selector: "//div[@id='sponsor-button']",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [PAGE_TYPES.VIDEO],
        label: "Join Button",
        category: "Video Player",
    },
    {
        id: "video-likes-dislikes",
        selector: "//button[contains(@aria-label, 'like this video')]/ancestor::segmented-like-dislike-button-view-model",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [PAGE_TYPES.VIDEO],
        label: "Likes / Dislikes",
        category: "Video Player",
    },
    {
        id: "video-share",
        selector: "//button[@aria-label='Share']/ancestor::yt-button-view-model",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [PAGE_TYPES.VIDEO],
        label: "Share Button",
        category: "Video Player",
    },
    {
        id: "video-download",
        selector: "//ytd-download-button-renderer",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [PAGE_TYPES.VIDEO],
        label: "Download Button",
        category: "Video Player",
    },
    {
        id: "video-thanks",
        selector: "//button[@aria-label='Thanks']/ancestor::yt-button-view-model",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [PAGE_TYPES.VIDEO],
        label: "Thanks Button",
        category: "Video Player",
    },
    {
        id: "video-save",
        selector: "//button[@aria-label='Save to playlist']/ancestor::yt-button-view-model",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [PAGE_TYPES.VIDEO],
        label: "Save Button",
        category: "Video Player",
    },
    {
        id: "video-clip",
        selector: "//button[@aria-label='Clip']/ancestor::yt-button-view-model",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [PAGE_TYPES.VIDEO],
        label: "Clip Button",
        category: "Video Player",
    },
    {
        id: "video-collapsed-buttons",
        selector: "//button[@aria-label='More actions']/ancestor::yt-button-shape",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [PAGE_TYPES.VIDEO],
        label: "More Options (Three Dots)",
        category: "Video Player",
    },
    {
        id: "video-description",
        selector: "//div[@id='description-inner']/parent::div",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [PAGE_TYPES.VIDEO],
        label: "Description Box",
        category: "Video Player",
    },
    {
        id: "video-views",
        selector: "//div[@id='view-count'] | (//yt-formatted-string[@id='info']/span)[position()<3]",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [PAGE_TYPES.VIDEO],
        label: "View Count",
        category: "Video Player",
    },
    {
        id: "video-people-mentioned-description",
        selector: "//yt-video-attributes-section-view-model",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [PAGE_TYPES.VIDEO],
        label: "People Mentioned (Desc)",
        category: "Video Player",
    },
    {
        id: "video-chapters-description",
        selector: "//ytd-horizontal-card-list-renderer[contains (@class, 'ytd-structured-description-content-renderer')]",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [PAGE_TYPES.VIDEO],
        label: "Chapters (Desc)",
        category: "Video Player",
    },
    {
        id: "video-transcription-description",
        selector: "//ytd-video-description-transcript-section-renderer",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [PAGE_TYPES.VIDEO],
        label: "Transcript (Desc)",
        category: "Video Player",
    },
    {
        id: "video-channel-links-description",
        selector: "//ytd-video-description-infocards-section-renderer",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [PAGE_TYPES.VIDEO],
        label: "Channel Links  (Desc)",
        category: "Video Player",
    },
    {
        id: "video-live-chat-replay",
        selector: "//div[@id='teaser-carousel']",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [PAGE_TYPES.VIDEO],
        label: "Live Chat Replay",
        category: "Video Player",
    },
    {
        id: "video-summary-ai-generated",
        selector: "//div[@id='expandable-metadata']",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [PAGE_TYPES.VIDEO],
        label: "AI Summary",
        category: "Video Player",
    },
    {
        id: "video-comments",
        selector: "//ytd-comments[@id='comments']",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [PAGE_TYPES.VIDEO],
        label: "Comments",
        category: "Video Player",
    },
    {
        id: "video-comments-avatars",
        selector: "//ytd-comments[@id='comments']//div[@id='author-thumbnail']/a",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [PAGE_TYPES.VIDEO],
        label: "Comment Avatars",
        category: "Video Player",
    },
    {
        id: "video-comments-replies",
        selector: "//ytd-comments[@id='comments']//div[@id='replies']",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [PAGE_TYPES.VIDEO],
        label: "Comment Replies",
        category: "Video Player",
    },
    {
        id: "video-categories-games",
        selector: "//ytd-rich-metadata-row-renderer/../..",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [PAGE_TYPES.VIDEO],
        label: "Game/Category Cards",
        category: "Video Player",
    },
    {
        id: "video-offer-module",
        selector: "//div[@id='offer-module']",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [PAGE_TYPES.VIDEO],
        label: "Offer Module (Merch)",
        category: "Video Player",
    },
    {
        id: "video-tabs",
        selector: "//yt-related-chip-cloud-renderer",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [PAGE_TYPES.VIDEO],
        label: "Related Video Tabs",
        category: "Video Player",
    },
    {
        id: "video-suggested-videos",
        selector: "//div[@id='contents']/parent::ytd-item-section-renderer[contains(@class, 'watch-next')]",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [PAGE_TYPES.VIDEO],
        label: "Related Videos (Sidebar)",
        category: "Video Player",
    },
    {
        id: "video-suggested-videos-new-badge",
        selector: "//ytd-compact-video-renderer//div/ytd-badge-supported-renderer[.//div[contains(@class, 'badge')]]",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [PAGE_TYPES.VIDEO],
        label: "'New' Badge in Sidebar",
        category: "Video Player",
    },
    {
        id: "video-suggested-shorts",
        selector: "//div[@id='contents']/parent::ytd-item-section-renderer[contains(@class, 'watch-next')]//ytd-reel-shelf-renderer",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [PAGE_TYPES.VIDEO],
        label: "Shorts in Sidebar",
        category: "Video Player",
    },
    {
        id: "video-end-screen",
        selector: "//div[contains(@class, 'ytp-endscreen-content')]",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [PAGE_TYPES.VIDEO],
        label: "End Screen Suggestions",
        category: "Video Player",
    },
    {
        id: "video-shorts-description",
        selector: "//ytd-structured-description-content-renderer//ytd-reel-shelf-renderer",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [PAGE_TYPES.VIDEO],
        label: "Shorts in Description",
        category: "Video Player",
    },
    {
        id: "stream-show-chat",
        selector: "//div[@id='show-hide-button']",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [PAGE_TYPES.VIDEO],
        label: "Show/Hide Chat Button",
        category: "Video Player",
    },
    {
        id: "video-settings-playback-speed",
        selector: "//div[@role='menuitem'][.//*[local-name() = 'svg']//*[local-name() = 'path' and @d='M10,8v8l6-4L10,8L10,8z M6.3,5L5.7,4.2C7.2,3,9,2.2,11,2l0.1,1C9.3,3.2,7.7,3.9,6.3,5z            M5,6.3L4.2,5.7C3,7.2,2.2,9,2,11 l1,.1C3.2,9.3,3.9,7.7,5,6.3z            M5,17.7c-1.1-1.4-1.8-3.1-2-4.8L2,13c0.2,2,1,3.8,2.2,5.4L5,17.7z            M11.1,21c-1.8-0.2-3.4-0.9-4.8-2 l-0.6,.8C7.2,21,9,21.8,11,22L11.1,21z            M22,12c0-5.2-3.9-9.4-9-10l-0.1,1c4.6,.5,8.1,4.3,8.1,9s-3.5,8.5-8.1,9l0.1,1 C18.2,21.5,22,17.2,22,12z']]",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [PAGE_TYPES.VIDEO],
        label: "Playback Speed Option",
        category: "Video Player",
    },
    {
        id: "video-settings-sleep-timer",
        selector: "//div[@role='menuitem'][.//*[local-name() = 'svg']//*[local-name() = 'path' and @d='M16.67,4.31C19.3,5.92,21,8.83,21,12c0,4.96-4.04,9-9,9c-2.61,0-5.04-1.12-6.72-3.02C5.52,17.99,5.76,18,6,18 c6.07,0,11-4.93,11-11C17,6.08,16.89,5.18,16.67,4.31 M14.89,2.43C15.59,3.8,16,5.35,16,7c0,5.52-4.48,10-10,10 c-1,0-1.97-0.15-2.89-0.43C4.77,19.79,8.13,22,12,22c5.52,0,10-4.48,10-10C22,7.48,19,3.67,14.89,2.43L14.89,2.43z M12,6H6v1h4.5 L6,10.99v0.05V12h6v-1H7.5L12,7.01V6.98V6L12,6z']]",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [PAGE_TYPES.VIDEO],
        label: "Sleep Timer Option",
        category: "Video Player",
    },
    {
        id: "video-progress-bar-dot",
        selector: "//div[@class='ytp-scrubber-container']",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [PAGE_TYPES.VIDEO],
        label: "Progress Bar Dot",
        category: "Video Player",
    },
    {
        id: "youtube-progress-bar",
        selector: "//div[contains(@class,'ytp-play-progress')]",
        checked: false,
        property: BACKGROUND,
        style: "#F03", // Custom color
        pageTypes: [PAGE_TYPES.VIDEO],
        label: "Neon Red Progress Bar",
        category: "Video Player",
    },

    // --- Other Pages ---
    {
        id: "subscriptions-shorts",
        selector: "//ytd-rich-shelf-renderer/../.. | //ytd-rich-shelf-renderer",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [PAGE_TYPES.SUBSCRIPTIONS],
        label: "Shorts in Subscriptions",
        category: "Other",
    },
    {
        id: "search-shorts",
        selector: "//ytd-reel-shelf-renderer",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [PAGE_TYPES.SEARCH],
        label: "Shorts in Search",
        category: "Other",
    },
    {
        id: "search-people-also-searched",
        selector: "//div[@id='contents']/ytd-horizontal-card-list-renderer",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [PAGE_TYPES.SEARCH],
        label: "People Also Searched",
        category: "Other",
    },
    {
        id: "trending-shorts",
        selector: "//ytd-video-renderer[.//a[contains(@href, '/shorts')]]",
        checked: false,
        property: DISPLAY,
        style: DISPLAY_NONE,
        pageTypes: [PAGE_TYPES.TRENDING],
        label: "Shorts in Trending",
        category: "Other",
    },
    {
        id: "channel-trailer",
        selector: "//*[@id='c4-player']",
        checked: false,
        pageTypes: [PAGE_TYPES.VIDEO],
        label: "Suggested Videos (Right Side)",
        category: "Video Player",
    },

];

// Helper to categorize for UI
export const getCategorizedElements = () => {
    const categories: Record<string, YoutubeElement[]> = {};
    DEFAULT_ELEMENTS.forEach(el => {
        const cat = el.category || "Other";
        if (!categories[cat]) categories[cat] = [];
        categories[cat].push(el);
    });
    return categories;
}
